import { useState, Fragment } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Modal } from 'components';

const Home: NextPage = () => {
  let [isOpen, setIsOpen] = useState(false);
  return (
    <div className="flex min-h-screen justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal
        isOpen={isOpen}
        onClose={() => setIsOpen(false)}
        title="Contact me"
        description="Something about contacting me"
      >
        <p>
          Are you sure you want to deactivate your account? All of your data
          will be permanently removed. This action cannot be undone.
        </p>
      </Modal>
      <button onClick={() => setIsOpen(true)}>
        open ({isOpen ? 'y' : 'n'})
      </button>
      <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
        <div className="px-6 py-4">
          <div className="font-bold text-xl mb-2">Next + Tailwind ❤️</div>
          <p className="text-grey-darker text-base">
            Next and Tailwind CSS are a match made in heaven, check out this
            article on how you can combine these two for your next app.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Home;
